namespace WadSharp.Parts
{
    /// <summary>
    ///  Contains subsectors used for GL nodes. Generated by the node builder. 
    /// </summary>
    public class WADGLSubSector
    {
        /// <summary>
        /// Seg count.
        /// </summary>
        public uint SegCount { get; set; }

        /// <summary>
        /// Index of the first seg in the segs array.
        /// </summary>
        public uint FirstSegIdx { get; set; }
    }
}
